NO_TICKET: Intermittent test failure of RequestFiltersIntegrationTest fix
Alfresco/hxinsight-connector pull request #215
Opened 2024-03-12 11:54 UTC by krdabrowski

2024-03-12 12:05 UTC, mpichura approved these changes
LGTM, should we reset requests in SFS Wire Mock as well?

2024-03-12 12:05 UTC, mpichura commented on live-ingester/src/integration-test/java/org/alfresco/hxi_connector/live_ingester/util/E2ETestBase.java
> +        hxInsightMock.resetRequests();
```suggestion
        hxInsightMock.resetRequests();
        sfsMock.resetRequests();
```

2024-03-13 10:37 UTC, tpage-alfresco commented on live-ingester/src/main/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/filter/AspectFilterApplier.java
> +        return CollectionUtils.isEmpty(allowed) || (CollectionUtils.isNotEmpty(aspectNames) && aspectNames.containsAll(allowed));
I mentioned on Maciej's PR that I think the original logic was correct here.

2024-03-13 10:38 UTC, tpage-alfresco commented on live-ingester/src/test/java/org/alfresco/hxi_connector/live_ingester/adapters/messaging/repository/filter/AspectFilterApplierTest.java
> +        assertFalse(result);
This should be `assertTrue` because the node has `aspect1 OR aspect2 AND NOT aspect3`

2024-03-13 10:39 UTC, tpage-alfresco requested changes
I think this has the same logic issue as Maciej's PR.

2024-03-13 11:26 UTC, krdabrowski commented
@tpage-alfresco @mpichura I've reverted changes in logic and updated tests

2024-03-13 13:51 UTC, tpage-alfresco approved these changes
LGTM

2024-03-13 14:43 UTC, mpichura approved these changes
Handle the conflicts and we can merge that mapper fix.

2024-03-13 15:17 UTC, merged